# Generated by Django 6.0.8 on 2026-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
